language: go

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

go:
  - 1.13.x

sudo: required

services:
  - docker
before_install:
  - docker system prune -af
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - /bin/sh -c './build/build.sh'
deploy:
  skip_cleanup: true
  provider: script
  script:
    # push to dockerhub & heroku
    - /bin/sh -c './build/push.sh'
  on:
    branch: master
